dirs:
  - .

excludedDirs:
  - bolt-contracts/lib
  - testnets/helder

useGitIgnore: true

ignorePatterns:
  # some websites use anti-scraping that will block linkspector requests
  - pattern: "^https://.*etherscan.io/.*$"
  - pattern: "^https://.*docs.eigenlayer.xyz/.*$"

  # endpoints that are not meant to be accessed by linkspector
  - pattern: "^https://rpc-.*.bolt.chainbound.io/rpc"

  # relay endpoints don't need to be checked
  - pattern: "^https://.*relay-holesky.bolt.chainbound.io"
  - pattern: "^https://.*holesky-preconf.titanrelay.xyz"
  - pattern: "^https://.*preconfs-holesky.aestus.live"
  - pattern: "^https://.*bloxroute.holesky.blxrbdn.com"
