dirs:
  - .

excludedDirs:
  - bolt-contracts/lib
  - testnets/helder

useGitIgnore: true

ignorePatterns:
  - pattern: "^https://.*etherscan.io/.*$"
  - pattern: "^https://.*docs.eigenlayer.xyz/.*$"
