name: Bug Report
description: Create a bug report
labels: ["T: bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

        If you believe you have found a vulnerability, please provide details [here](mailto:admin@chainbound.io) instead.
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Please provide any steps you think might be relevant to reproduce the bug.
      placeholder: |
        Steps to reproduce:

        1. Start '...'
        2. Then '...'
        3. Check '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Node logs
      description: |
        If applicable, please provide the logs leading up to the bug.
      render: text
    validations:
      required: false
  - type: dropdown
    id: platform
    attributes:
      label: Platform(s)
      description: What platform(s) did this occur on?
      multiple: true
      options:
        - Linux (x86)
        - Linux (ARM)
        - Mac (Intel)
        - Mac (Apple Silicon)
        - Windows (x86)
        - Windows (ARM)
    validations:
      required: true
  - type: textarea
    id: bolt-version
    attributes:
      label: What version/commit are you on?
      description: This can be obtained with `bolt-sidecar --version` or by checking the container tags.
    validations:
      required: true
  - type: dropdown
    id: run-mode
    attributes:
      label: Running Mode
      description: How are you running bolt?
      options:
        - Docker mode
        - Commit-Boost mode
        - Native mode
    validations:
      required: true
  - type: textarea
    id: network
    attributes:
      label: Which chain / network are you on?
      description: Mainnet or Holesky?
    validations:
      required: true
  - type: dropdown
    id: el-type
    attributes:
      label: Which execution layer client are you using?
      options:
        - Geth
        - Nethermind
        - Besu
        - Erigon
        - Reth
        - Other
    validations:
      required: true
  - type: dropdown
    id: cl-type
    attributes:
      label: Which consensus layer client are you using?
      options:
        - Prysm
        - Lighthouse
        - Teku
        - Nimbus
        - Other
    validations:
      required: true
  - type: input
    attributes:
      label: If you've built bolt from source, provide the full command you used
    validations:
      required: false
