# ports
port = 8000
metrics_port = 3300

# node urls
execution_api_url = "http://localhost:8545"
beacon_api_url = "http://localhost:5052"
engine_api_url = "http://localhost:8551"
engine_jwt_hex = "0x573300d0cd9a8e253429998a3ceecf358aa4868d96772d1344a80144d3b7b593"

# constraints options
constraints_api_url = "http://localhost:3030"
constraints_proxy_port = 18551

validator_indexes = "0..64"
fee_recipient = "0x0155ef0C0fE550C297c1216585e0DE1478EA30e4"

builder_private_key = "0x359c156600e1f5715a58c9e09f17c8d04e7ee3a9f88b39f6e489ffca0148fabe"
commitment_private_key = "0x359c156600e1f5715a58c9e09f17c8d04e7ee3a9f88b39f6e489ffca0148fabe"

# chain options
[chain]
chain = "Kurtosis"
slot_time = 2
commitment_deadline = 8000

[telemetry]
metrics_port = 3300
disable_metrics = false

# signing options
[constraint_signing]
constraint_private_key = "0x359c156600e1f5715a58c9e09f17c8d04e7ee3a9f88b39f6e489ffca0148fabe"
delegations_path = "./delegations.json"
